### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by dwijnand** [scalaz/testz#30]
I happen to notice that testz isn't present in https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md#testing-libraries.

For adoption, it might be useful to be there.

I'm not sure if there are any blockers to this.

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/pull/830 adds testz to the 2.12 community build, and I've merged the change into the 2.13 community build as well, and at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1694/ we see `Project testz-----------------------: SUCCESS (project rebuilt ok)`, so that's a good sign that this might be pretty easy

**Comment by xuwei-k** [comment]
- https://github.com/scalaz/testz/commit/0ddc7caca7f58c69101054b8a61ec0c8f2aceafb
- https://github.com/scalaz/testz/commit/5d22e725cdd2e6e4dffd8d65047775e3351048a9
- https://github.com/scalaz/testz/releases/tag/v0.0.6
